jodconverter:
  local:
    enabled: true
    # openoffice安装路径
    office-home: C:\Program Files (x86)\OpenOffice 4
    max-tasks-per-process: 64
    #openoffice端口号
    port-numbers: 8100

server:
  port: 8090
